"""
Bannercard Component.

This component was auto-generated by fletx.

🛠️ Customization Guide:
- You can change the parent class (`ft.Container`) to inherit from any other Flet control.
  → Example: `ft.Text`, `ft.Row`, `ft.Column`, or any custom Flet widget.
- You can add or modify internal reactive attributes.
  → Example: `self.title: RxStr = rx_title`
- You can define simple or advanced bindings using the fletx decorators
"""

from flet import *
from fletx.core import (
    RxStr
)
from fletx.decorators import (
    simple_reactive
)

from app.models import BannerInfo
from app.utils.theme import dark_gradient


class Bannercard(Container): 
    """Reactive Bannercard Widget"""

    def __init__(self, item: BannerInfo, **kwargs):
        # 🛠️ kwargs allows passing any Flet control arguments like bgcolor, padding, etc.
        super().__init__(
            height = 150,
            padding = 15,
            border_radius = 12,
            # gradient = dark_gradient,
            **kwargs
        )
        
        self.item = item
        self.bgcolor = self.item.color or Colors.PRIMARY
        self.content = self.build()

    def build(self):
        """Build Banner Card Content."""

        return Row(
            expand = True,
            controls = [
                Column(
                    expand = True,
                    spacing = 4,
                    width = self.width * .6,
                    alignment = MainAxisAlignment.CENTER,
                    horizontal_alignment = CrossAxisAlignment.START,
                    controls = [
                        Text(
                            self.item.title,
                            size = 14,
                            weight = FontWeight.W_500,
                            color = Colors.WHITE
                        ),
                        Text(
                            self.item.description,
                            size = 12,
                            color = Colors.WHITE
                        ),
                         Container(
                            # expand = True,
                            ink = True,
                            padding = 8,
                            bgcolor = Colors.SURFACE,
                            border_radius = 12,
                            on_click = lambda _: None,
                            content = Text(
                                'Learn more',
                                style = TextStyle(
                                    color = Colors.ON_SURFACE
                                )
                            )
                        ),
                    ]
                ),

                # IMAGE
                Image(
                    src = self.item.image,
                    fit = ImageFit.FIT_HEIGHT
                )
            ]
        )

    