"""
Cartitemlist Component.

This component was auto-generated by fletx.

🛠️ Customization Guide:
- You can change the parent class (`ft.Container`) to inherit from any other Flet control.
  → Example: `ft.Text`, `ft.Row`, `ft.Column`, or any custom Flet widget.
- You can add or modify internal reactive attributes.
  → Example: `self.title: RxStr = rx_title`
- You can define simple or advanced bindings using the fletx decorators
"""

import flet as ft
from fletx.core import (
    RxList
)
from fletx.decorators import (
    reactive_list
)
from fletx.utils import get_page

from app.models import CartItem
from .cartitem_component import Cartitem
from .emptylist_component import EmptylistComponent

@reactive_list(
    items_attr = 'items',
    item_builder = lambda item, index : Cartitem(
        item = item
    ),
    empty_builder = lambda: EmptylistComponent(
        message = 'Your Shopping cart is emplty',
        width = get_page().width
        # expand = True
    )
)
class CartItemlist(ft.Column):
    """Reactive Cartitemlist Widget"""

    def __init__(self, items: RxList[CartItem], **kwargs):
        # 📝 Define your reactive properties
        self.items: RxList[CartItem] = items

        # 🛠️ kwargs allows passing any Flet control arguments like bgcolor, padding, etc.
        super().__init__(**kwargs)
