"""
Emptylist Component.

This component was auto-generated by fletx.

🛠️ Customization Guide:
- You can change the parent class (`ft.Container`) to inherit from any other Flet control.
  → Example: `ft.Text`, `ft.Row`, `ft.Column`, or any custom Flet widget.
- You can add or modify internal reactive attributes.
  → Example: `self.title: RxStr = rx_title`
- You can define simple or advanced bindings using the fletx decorators
"""

from flet import *
# from fletx.core import (
#     RxStr
# )
# from fletx.decorators import (
#     simple_reactive
# )


class EmptylistComponent(Container):
    """Reactive Emptylist Widget"""

    def __init__(
        self, 
        message: str = '', 
        img: str = 'empty-list.webp',
        img_size: int = 100,
        **kwargs
    ):
        # 📝 Define your reactive properties
        self.message = message
        self.img = img
        self.img_size = img_size
        # 🛠️ kwargs allows passing any Flet control arguments like bgcolor, padding, etc.
        super().__init__(
            expand = True,
            border_radius = 12,
            bgcolor = Colors.SURFACE,
            **kwargs
        )

        self.content = self.build()

    def build(self):
        """Build content"""

        return Column(
            expand = True,
            alignment = MainAxisAlignment.CENTER,
            horizontal_alignment = CrossAxisAlignment.CENTER,
            controls = [
                Image(
                    src = self.img,
                    # width = self.width,
                    height = self.img_size,
                    fit = ImageFit.FIT_HEIGHT
                ),
                Text(
                    self.message,
                    size = 14,
                    weight = FontWeight.W_500,
                    color = Colors.ON_SURFACE_VARIANT
                ),
                Text(
                    "Try changing the filters or adding new items.",
                    size = 12,
                    color = Colors.ON_SURFACE_VARIANT
                )
            ]
        )