"""
Orderlist Component.

This component was auto-generated by fletx.

🛠️ Customization Guide:
- You can change the parent class (`ft.Container`) to inherit from any other Flet control.
  → Example: `ft.Text`, `ft.Row`, `ft.Column`, or any custom Flet widget.
- You can add or modify internal reactive attributes.
  → Example: `self.title: RxStr = rx_title`
- You can define simple or advanced bindings using the fletx decorators
"""

import flet as ft
from fletx.core import (
    RxList
)
from fletx.decorators import (
    reactive_list
)

from .ordercard_component import OrderCard
from .emptylist_component import EmptylistComponent
from app.models import OrderInfo

@reactive_list(
    items_attr = 'orders',
    item_builder = lambda item, index : OrderCard(
        order = item
    ),
    empty_builder = lambda: EmptylistComponent(
        message = 'Your Shopping cart is emplty',
        # expand = True
    )
)
class OrderList(ft.ListView):
    """Reactive Orderlist Widget"""

    def __init__(self, orders: RxList[OrderInfo], **kwargs):
        # 📝 Define your reactive properties
        self.orders: RxList[OrderInfo] = orders

        # 🛠️ kwargs allows passing any Flet control arguments like bgcolor, padding, etc.
        super().__init__(**kwargs)