"""
Ordercard Component.

This component was auto-generated by fletx.

🛠️ Customization Guide:
- You can change the parent class (`ft.Container`) to inherit from any other Flet control.
  → Example: `ft.Text`, `ft.Row`, `ft.Column`, or any custom Flet widget.
- You can add or modify internal reactive attributes.
  → Example: `self.title: RxStr = rx_title`
- You can define simple or advanced bindings using the fletx decorators
"""

from flet import *
from fletx.core import (
    RxStr
)
# from fletx.decorators import (
#     simple_reactive
# )

from app.models import OrderInfo

class OrderCard(Container):    # 🧩 You can replace ft.Container with any other Flet control
    """Reactive Ordercard Widget"""

    def __init__(self, order: OrderInfo, **kwargs):
        # 📝 Define your reactive properties
        self.order: OrderInfo = order

        # 🛠️ kwargs allows passing any Flet control arguments like bgcolor, padding, etc.
        super().__init__(
            height = 130,
            bgcolor = Colors.SURFACE,
            border_radius = 15,
            padding = 10,
            **kwargs
        )

        # Build content
        self.content = self.build()

    def build(self):
        """Build Order Item content."""

        return Row(
            expand = True,
            spacing = 15,
            controls = [
                #  Image
                Image(
                    height = 110,
                    width = 110,
                    fit = ImageFit.FILL,
                    border_radius = 10,
                    src = self.order.articles[0].product.medias[0].file,
                ),

                # Name
                Column(
                    expand = True,
                    spacing = 5,
                    controls = [
                        Text(
                            f'{self.order.articles[0].product.name[:150]}',
                            size = 14,
                            max_lines = 2,
                            weight = FontWeight.BOLD
                        ),
                        Text(
                            f'Total Items {len(self.order.articles)}',
                            size = 14,
                            max_lines = 2,
                            weight = FontWeight.W_400
                        ),
                        Row(
                            expand = True,
                            alignment = MainAxisAlignment.SPACE_BETWEEN,
                            controls = [
                                # PRICE
                                Text(
                                    f"{self.order.total} FCFA",
                                    size = 14,
                                    color = Colors.PRIMARY,
                                    weight = FontWeight.BOLD,
                                    text_align = TextAlign.LEFT
                                ),

                                # DETAILS BUTTON
                                Container(
                                    ink = True,
                                    padding = 4,
                                    border_radius = 20,
                                    bgcolor = Theme.scaffold_bgcolor,
                                    content = Row(
                                        spacing = 5,
                                        controls = [
                                            Icon(
                                                Icons.CALENDAR_TODAY,
                                                color = Colors.BLUE_700
                                            ),
                                            Text(
                                                f"{self.order.created.date().isoformat()}",
                                                size = 14,
                                                color = Colors.with_opacity(
                                                    .7, Colors.ON_SURFACE
                                                ),
                                                weight = FontWeight.BOLD,
                                                text_align = TextAlign.LEFT
                                            )
                                        ]
                                    ),
                                ),
                            ]
                        )
                    ]
                )
            ]
        )
