"""
Productgrid Component.

This component was auto-generated by fletx.

🛠️ Customization Guide:
- You can change the parent class (`ft.Container`) to inherit from any other Flet control.
  → Example: `ft.Text`, `ft.Row`, `ft.Column`, or any custom Flet widget.
- You can add or modify internal reactive attributes.
  → Example: `self.title: RxStr = rx_title`
- You can define simple or advanced bindings using the fletx decorators
"""

import flet as ft
from fletx.core import (
    RxList
)
from fletx.decorators import (
    reactive_list
)

from .productcard_component import ProductCard
from .emptylist_component import EmptylistComponent

@reactive_list(
    items_attr = 'products',
    item_builder = lambda item, index : ProductCard(
        product = item,
        padding = 0,
        expand = True,
        border_radius = 10,
    ),
    empty_builder = lambda: EmptylistComponent (
        message = 'No Products'
    ),
    animate_changes = False
)
class ProductGrid(ft.GridView):    
    """Reactive Productgrid Widget"""

    def __init__(
        self, 
        products: RxList = RxList([]), 
        **kwargs
    ):
        # 📝 Define your reactive properties
        self.products: RxList = products

        # 🛠️ kwargs allows passing any Flet control arguments like bgcolor, padding, etc.
        super().__init__(**kwargs)
