"""
Productcard Component.

This component was auto-generated by fletx.

🛠️ Customization Guide:
- You can change the parent class (`ft.Container`) to inherit from any other Flet control.
  → Example: `ft.Text`, `ft.Row`, `ft.Column`, or any custom Flet widget.
- You can add or modify internal reactive attributes.
  → Example: `self.title: RxStr = rx_title`
- You can define simple or advanced bindings using the fletx decorators
"""

from flet import *
from fletx import FletX
from fletx.decorators import obx

from app.controllers import ProductsController
from app.models import ProductInfo

class ProductCard(Container):   
    """Reactive Productcard Widget"""

    def __init__(self, product: ProductInfo, **kwargs):
        # 📝 Define your reactive properties
        self.product: ProductInfo = product

        # 🛠️ kwargs allows passing any Flet control arguments like bgcolor, padding, etc.
        super().__init__(
            # bgcolor = Colors.SURFACE,
            **kwargs
        )

        # Inject controler
        self.productController: ProductsController = FletX.find(
            ProductsController, tag = 'product_ctrl'
        )

        # Build content
        self.content = self.build()

    @obx
    def like_btn(self):
        """Favorite button"""

        return IconButton(
            top = 10,
            right = 15,
            bgcolor = Colors.SURFACE,
            on_click = lambda _ : (
                None    #TODO: Call like action with product controller
                if self.productController._is_loading.value
                else None
            ),
            content = (
                ProgressRing(
                    height = 25,
                    width = 25,
                    color = Colors.ON_SURFACE
                )
                if self.productController._is_loading.value 
                else Icon(
                    Icons.FAVORITE,
                    color = Colors.ON_SURFACE,
                ) 
            )
        )

    def build(self):
        """Build Product Card content"""

        return Stack(
            expand = True,
            controls = [
                # PRODUCT INFOS DISPLAY
                Column(
                    spacing = 2,
                    expand = True,
                    # height = 110,
                    controls = [
                        # IMAGE
                        Container(
                            expand = True,
                            # height = 
                            bgcolor = Colors.SURFACE,
                            border_radius = 15,
                            clip_behavior = ClipBehavior.HARD_EDGE,

                            content = Image(
                                expand = True,
                                src = self.product.images[0],
                                fit = ImageFit.COVER
                            )
                        ),

                        # PRODUCT NAME
                        Column(
                            spacing = 5,
                            controls = [
                                Text(
                                    f'{self.product.title}',
                                    size = 14,
                                    weight = FontWeight.W_400
                                ),
                                Row(
                                    spacing = 15,
                                    alignment = MainAxisAlignment.START,
                                    controls = [
                                        Text(
                                            f'{self.product.price} FCFA',
                                            size = 16,
                                            weight = FontWeight.W_500
                                        ),

                                        Row(
                                            spacing = 0,
                                            alignment = MainAxisAlignment.START,
                                            controls = [
                                                Icon(
                                                    Icons.STAR_RATE_ROUNDED,
                                                    size = 24,
                                                    color = Colors.PRIMARY
                                                ),
                                                Text(
                                                    f'4.9',
                                                    size = 14,
                                                    weight = FontWeight.W_500,
                                                    color = Colors.ON_SURFACE_VARIANT
                                                )
                                            ]
                                        )
                                    ]
                                )
                            ]
                        )
                    ]
                ),

                # LIKE BUTTON
                self.like_btn()
            ]
        )

